### ISSUE TITLE
MIDI no CtrlMap

### ISSUE THREAD

**Issue by saelsimard** [IntentDev/Luminosity#12]
The setPar node in /Luminosity/database/ctrlMaps/MIDI doesn't seem to send the gadget its parameter.
Here is the error: ` File "/Luminosity/database/ctrlMaps/MIDI/setPar", line 29, in valueChange
AttributeError: 'NoneType' object has no attribute 'CtrlMap'`

TD version: 16620

**Comment by saelsimard** [comment]
Update: 
After clearing the map, it works for all sliders, but not clips in the banks.

`Traceback (most recent call last):
  File "/Luminosity/master/ui/clipLanes/clipLane0/clip2/triggerLC", line 9, in offToOn
  File "/Luminosity/local/modules/extPFMClips", line 174, in TriggerLC
  File "/Luminosity/local/modules/extPFMClips", line 92, in AssignClipCtrls
AttributeError: 'NoneType' object has no attribute 'store'`

**Comment by vjasterix** [comment]
Might be worth clearing the maps in the next build.

**Comment by vjasterix** [comment]
Saelismard, were you attempting this on a gen or just a standard movie clip?
