### ISSUE TITLE
cropping in 2d mode not working

### ISSUE THREAD

**Issue by tayotain** [IntentDev/Luminosity#13]
Sliders on crop not working on 2d mapping mode.

**Comment by vjasterix** [comment]
Hi Tayotain, 
I looked at the issue, seems like some container wierdness possibly introduced by the touchdesigner version. This won't go into master right now but you can fix this by downloading the tox below. In /Luminosity/utilities delete the warp component. And drag the warp.tox to the /Luminosity/utilities panel. Should solve the issue.

https://drive.google.com/open?id=1ut3OyB9eDDlhEeoGQCwBtVk6vXB4g6EG

**Comment by keithlostracco** [comment]
This is now fixed.
