### ISSUE TITLE
Document pro license requirement

### ISSUE THREAD

**Issue by justin-hackin** [IntentDev/Luminosity#17]
I noticed there were some operators (e.g. Shared Mem Out), that only work with a commercial or pro license e.g. in /Luminosity/master/toNodes. I think it would be nice to spell out this in the readme.

I'm not sure if it's related, but none of the channels have a proper preview so unfortunately I wasn't able to use this project 
![Screen Shot 2023-02-07 at 5 08 43 PM](https://user-images.githubusercontent.com/4888331/217378102-f7da79c0-c008-48b4-9711-4c1817eeb85e.png)

**Comment by vjasterix** [comment]
Shared mem etc are disabled by touchdesigner due to your license, not by Luminosity. Seems like you should be running an earlier version of touchdesigner supported by the application.

**Comment by justin-hackin** [comment]
@vjasterix there's no maximum version stated here. The docs say `TouchDesigner099 Official Build 2020.22080 or newer`. I have tried the latest and regressed to TouchDesigner.2020.28110 which would not start and TouchDesigner.2021.16960 which suffered the same issue.

**Comment by justin-hackin** [comment]
I confirmed the issue in the screenshot was fixed in a fork so closing this in favor of https://github.com/IntentDev/Luminosity/issues/18
