### ISSUE TITLE
Top menu crashes TD 

### ISSUE THREAD

**Issue by jimbobhunter** [IntentDev/Luminosity#2]
The file/top menu makes TD disappear after clicking a menu item. Repeatable on win 10 21150 when clicking between menu items even with a blank project, everything disappears after a few seconds. At one point I noticed that the session menu was showing the file menu just before it crashed.

**Comment by keithlostracco** [comment]
Looks like your running the experimental build of Touch.. you shouldn't
have the issue with the official build.

There are a number of issues with the experimental build of TD.
