### ISSUE TITLE
Channel previews not rendering and aux send only outputting pattern

### ISSUE THREAD

**Issue by djevo1** [IntentDev/Luminosity#7]
I just downloaded a new copy of Luminosity and noticed something odd. I am using the latest official non-commercial version of TD and see that the clip previews and aux channel previews are not functioning. This is on Mac OS high sierra. 
<img width="1908" alt="screen shot 2018-08-11 at 6 32 48 pm" src="https://user-images.githubusercontent.com/16768999/43996642-0a457258-9d95-11e8-8224-d12368ad1d00.png">

**Comment by OnketIndustries** [comment]
did you figure out how to work around this issue?

**Comment by keithlostracco** [comment]
Do you have "Internal" processing mode set in project settings?

**Comment by OnketIndustries** [comment]
yes, i do have project settings to internal.

**Comment by boomshokka** [comment]
i am having the same issue on os el capitan. Anyone has an idea on how to work around it?

**Comment by keithlostracco** [comment]
It seems thisis  a Mac only issue. I don't have a Mac but if someone would let me teamviewer into their computer I could try and fix the issue.

**Comment by boomshokka** [comment]
i would be really happy to let you teamviewer into my computer. It would be awesome to play around with this network. If you are really up for doing that contact me on hannesvorhauser@icloud.com and we can arrange some time.
