### ISSUE TITLE
3 issues with new version

### ISSUE THREAD

**Issue by ruvidan** [IntentDev/Luminosity#9]
This is amazing!  Thanks so much for your hard work!

I wanted to show three little bugs(?) that I stumbled across.  I'm attaching a Youtube link so you can see what I mean.

https://youtu.be/vqPdnXoZj5I
1. (in video) the clips box is empty even though there are clips in there.
2. (in video) when editing a network, creating a new operator - the window is stuck behind the window I'm on.
3. I couldn't get MIDI to work.  I was able to map my videos to a key, and the data was displaying that it was mapped - but when I exited the mapping mode and hit the keys, it didn't launch the video.

**Comment by keithlostracco** [comment]
Hi Ruvidan,

The first issue is known, see issue below.

The second issue is the way TD works with perform windows and floating
windows, the floating windows are always on top...

I'm not sure about the third I'll have to try and recreate it.
